# Generated by Django 4.2.7 on 2023-11-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('Nombre', models.CharField(max_length=200)),
                ('Viaje', models.TextField()),
                ('Puntuacion', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
