# Generated by Django 4.2.7 on 2023-12-30 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foro', '0002_alter_posts_puntuacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Viaje',
            new_name='Comentario',
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
