# Generated by Django 4.2.7 on 2023-12-31 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_rename_viaje_posts_comentario_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Nombre',
        ),
    ]
